### ISSUE TITLE
Delta Green Crits support, hard/extreme CoC support, BRP special support

### ISSUE THREAD

**Issue by apoapostolov** [caphosra/cthulhu_bot#23]
Please consider adding the following feature. Message me if you are only open to paid commissions. 

- Delta Green Crits. If the result is doubles (11, 22, 33) it is Critical Success or Failure when compared to value X (/dr)
- CoC Success Levels. Hard Success (result is =< 1/2 X) or Extreme success (result is =< 1/5 X) (/r)
- BRP Success Levels as presented on  p. 110 of the new BRP 2023 rulebook: (/br)

![image](https://user-images.githubusercontent.com/4083812/232025795-c8f49d3a-5bd6-4eb6-b190-f3080d7f66cb.png)

**Comment by caphosra** [comment]
Thank you for posting feature requests!
Those sound good to me and I decided to try to add these features as experimental. But I'm not sure I can implement these features nicely because I don't understand these rules enough, actually. So, after the implementations are over, please try these features and advise me:)

**Comment by apoapostolov** [comment]
I am active on Github and I check the issues inbox every few days so feel free to ask any questions I will answer them.

**Comment by apoapostolov** [comment]
Feel free to message me on Discord too, ApoApostolov#4622

**Comment by caphosra** [comment]
Thank you for waiting so long. Now, the features you requested are implemented as `/skdg`, `/sk7`, and `/skbrp` respectively on #34 :tada: If you see any strange behavior on this, let me know.

**Comment by caphosra** [comment]
I expect the changes to be reflected within 2-3 hours.

**Comment by apoapostolov** [comment]
Thank you so much!
